name: MailBox
description: In game mail
version: 1.1-SNAPSHOT
main: net.lethargiclion.mailbox.PluginMain
commands:
  sendmail:
    description: Send a message to a player!
  setmailbox:
    description: Set your mailbox chest!
