name: MailBox
description: In game mail
version: 1.0
main: net.lethargiclion.mailbox.PluginMain
commands:
  sendmail:
    description: Send a message to a player!
  setmailbox:
    description: Set your mailbox chest!
